{{- if .Values.serviceAccount.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: {{ include "deployment-supervisor.fullname" . }}-supervisor
rules:
- apiGroups:
  - ""
  - batch
  resources:
  - events
  - jobs
  - jobs/status
  - pods
  - pods/log
  - configmaps
  verbs:
  - get
  - list
  - create
  - watch
  - update
  - patch
  - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: null
  name: {{ include "deployment-supervisor.fullname" . }}-supervisor
  namespace: {{ .Release.Namespace}}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "deployment-supervisor.fullname" . }}-supervisor
subjects:
- kind: ServiceAccount
  name: {{ include "deployment-supervisor.serviceAccountName" . }}
  namespace: {{ .Release.Namespace}}
{{- end }}
